### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Eugenepolyt/cutKotlin#1]
1. В первую очередь прочитайте в Teams общие для всех замечания и исправьте их
2. Разрешаю (чтобы избавиться от костылей поменять синтаксис для range: сделать, например так: `-r <range>`

**Comment by Eugenepolyt** [comment]
> 1. В первую очередь прочитайте в Teams общие для всех замечания и исправьте их
> 2. Разрешаю (чтобы избавиться от костылей поменять синтаксис для range: сделать, например так: `-r <range>`

Исправил

**Comment by gagarski** [comment]
Второе ок, по первому далеко не всё (запись тоже можно обобщить, всё ещё храните список строк в памяти, хотя без этого можно обойтись)

**Comment by Eugenepolyt** [comment]
> Второе ок, по первому далеко не всё (запись тоже можно обобщить, всё ещё храните список строк в памяти, хотя без этого можно обойтись)

Исправил , вроде... =)

**Comment by gagarski** [comment]
1. Сейчас немного пугает логика с range и регексами кнутри класса `Cut`. Лучше бы этот range допарсить до запуска, а внутри `Cut` работать уже с парой чисел (в виде Pair или отдельного класса)
2. https://github.com/Eugenepolyt/cutKotlin/blob/8ec257104bd9115c42c538b913389234f27960f6/src/main/kotlin/cut/Cut.kt#L9-L12

    Куда-то очень далеко уехала аннотация. А зачем она вообще, сможете мне объяснить на занятии?

3. Немного кривая логика с пустой строкой в имени файла. Во-первых, в качестве специального значения можно использовать `null`. Во-вторых, args4j позволяет сделать аргумент типа `File`, можно этим воспользоваться.

**Comment by Eugenepolyt** [comment]
> 1. Сейчас немного пугает логика с range и регексами кнутри класса `Cut`. Лучше бы этот range допарсить до запуска, а внутри `Cut` работать уже с парой чисел (в виде Pair или отдельного класса)
> 2. https://github.com/Eugenepolyt/cutKotlin/blob/8ec257104bd9115c42c538b913389234f27960f6/src/main/kotlin/cut/Cut.kt#L9-L12
>    
>    Куда-то очень далеко уехала аннотация. А зачем она вообще, сможете мне объяснить на занятии?
> 3. Немного кривая логика с пустой строкой в имени файла. Во-первых, в качестве специального значения можно использовать `null`. Во-вторых, args4j позволяет сделать аргумент типа `File`, можно этим воспользоваться.

Исправил, да смогу
